apiVersion: v1
kind: Pod
metadata:
  name: graphonomy-pod-gpu
  labels:
    app: graphonomy-pod-gpu
spec:
  restartPolicy: OnFailure
  containers:
  - name: graphonomy-container-gpu
    image: gcr.io/myproject-292103/graphonomy-image
    ports:
    - containerPort: 5000
      name: http-server
    #command: ["nvidia-smi"]
    resources:
      limits:
        nvidia.com/gpu: 1
