apiVersion: v1
kind: Service
metadata:
  name: graphonomy-server-cpu
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: graphonomy-pod-cpu  # デプロイメント定義ファイルで定義した Pod の識別名。app:sample-pod のラベルがつけられた Pod を通信先とする
